version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_dw
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: staging_dw
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

  pentaho:
    image: knowbi/pentaho-di:latest
    container_name: pentaho_pdi
    restart: always
    ports:
      - "58080:58080" # Acceso remoto vía VNC web
    environment:
      USER: admin
      PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - ./pdi:/home/pentaho/.kettle # Para guardar configuraciones y jobs
